import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Scissors, Sparkles, Leaf, Clock, CalendarDays, Check, MoveUpRight } from 'lucide-react';
import BotanicalScene from '../components/botanical-scene';

export default function Home() {
  return <>
    <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="line" /> YOUR EVERYDAY, REIMAGINED</p><h1>A little time<br />for <em>you.</em></h1><p className="hero-description">Beautiful hair. A quieter mind. A fresh feeling.<br />Step into a thoughtfully imagined salon experience.</p><div className="hero-actions"><Link href="/book" className="button">Find your moment<ArrowUpRight size={18} /></Link><Link href="/services" className="text-link">Explore the menu<ArrowRight size={17} /></Link></div><div className="hero-meta"><span><MapPinIcon />MARGAO, GOA</span><span><Clock size={14} />BOOK AT YOUR OWN PACE</span></div></div><div className="hero-visual"><img className="hero-image" src="https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=1400&q=85" alt="Stylist creating a carefully finished hairstyle in a bright salon" fetchPriority="high" /><div className="image-shade" /><div className="hero-image-label"><span>THE ART OF FEELING GOOD</span><Leaf size={22} strokeWidth={1} /></div><div className="hero-orbit"><BotanicalScene compact /></div><div className="hero-float-card"><span className="float-icon"><Sparkles size={20} strokeWidth={1.3} /></span><div>A fresh chapter<small>Starts with a little self-care.</small></div></div><span className="hero-vertical">HAIR · BEAUTY · A MOMENT FOR YOU</span></div><div className="hero-index"><span>01 — THE EDEN EXPERIENCE</span><span>SCROLL TO DISCOVER ↓</span></div></section>
    <div className="marquee" aria-hidden="true"><div>{[1, 2, 3].map(i => <span key={i}>CARE IN EVERY DETAIL <Leaf size={18} /> ROOTED IN YOU <Leaf size={18} /> A FRESH PERSPECTIVE <Leaf size={18} /></span>)}</div></div>
    <section className="section services-preview" data-reveal><div className="section-heading"><div><p className="eyebrow">01 / THE SAMPLE MENU</p><h2>Your mood.<br />Your <em>moment.</em></h2></div><div><p>From a subtle refresh to a whole new look,<br />find a service that feels like you.</p><Link href="/services" className="text-link">View all services<ArrowUpRight size={18} /></Link></div></div><div className="service-preview-grid"><Link href="/services?category=Hair" className="service-photo-card"><div className="service-card-image"><img src="https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=900&q=80" alt="Salon stylist brushing a client's hair" loading="lazy" /><span className="round-arrow"><ArrowUpRight size={22} /></span></div><span className="eyebrow">CUT · STYLE · COLOUR</span><h3>Hair, with personality.</h3><p>Good hair days, thoughtfully made.</p></Link><Link href="/services?category=Skin" className="service-photo-card"><div className="service-card-image"><img src="https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80" alt="Calming facial skincare treatment" loading="lazy" /><span className="round-arrow"><ArrowUpRight size={22} /></span></div><span className="eyebrow">SKIN · CARE · GLOW</span><h3>A softer kind of glow.</h3><p>Time to pause. Space to reset.</p></Link><Link href="/services?category=Wellness" className="service-photo-card"><div className="service-card-image"><img src="https://images.unsplash.com/photo-1600948836101-f9ffda59d250?auto=format&fit=crop&w=900&q=80" alt="Warmly lit salon with mirrors and styling chairs" loading="lazy" /><span className="round-arrow"><ArrowUpRight size={22} /></span></div><span className="eyebrow">TREATMENT · RESTORE · RENEW</span><h3>A little extra care.</h3><p>Small rituals. A beautiful difference.</p></Link></div></section>
    <section className="philosophy-section" data-reveal><div className="philosophy-visual"><BotanicalScene /><span className="visual-label">THOUGHTFULLY CRAFTED, NATURALLY YOU</span></div><div className="philosophy-copy"><p className="eyebrow">02 / THE FEELING</p><h2>Come as you are.<br />Leave feeling<br /><em>like yourself.</em></h2><p>We imagined Eden as a place where the details feel effortless—from finding the right service to choosing a time that fits your day.</p><p>This independent concept brings a personal touch to a familiar neighbourhood salon experience.</p><Link href="/about" className="text-link">The story behind the concept<ArrowUpRight size={18} /></Link><div className="philosophy-values"><span><Leaf size={20} strokeWidth={1.3} />Considered care</span><span><Scissors size={20} strokeWidth={1.3} />A personal touch</span><span><Clock size={20} strokeWidth={1.3} />Your time matters</span></div></div></section>
    <section className="section booking-intro" data-reveal><div className="section-heading"><div><p className="eyebrow">03 / MADE SIMPLE</p><h2>A good day is<br />a few <em>clicks away.</em></h2></div><Link href="/book" className="button">Book a sample visit<ArrowUpRight size={18} /></Link></div><div className="steps-grid"><div><span className="step-number">01</span><Scissors size={24} strokeWidth={1.2} /><h3>Find your service</h3><p>A quick refresh or something new.<br />Choose what feels right.</p></div><div><span className="step-number">02</span><CalendarDays size={24} strokeWidth={1.2} /><h3>Pick your moment</h3><p>Explore available slots and choose<br />the time that fits your day.</p></div><div><span className="step-number">03</span><Check size={24} strokeWidth={1.2} /><h3>You're all set</h3><p>Get your booking details and manage<br />your visit in one simple place.</p></div></div></section>
    <section className="closing-cta" data-reveal><Leaf size={34} strokeWidth={1} /><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Make a little<br /><em>room for you.</em></h2><Link href="/book" className="button light">Let's find your moment<ArrowUpRight size={18} /></Link><span>TRY THE COMPLETE DEMO BOOKING EXPERIENCE</span></section>
  </>;
}
function MapPinIcon() { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" width="14" height="14" aria-hidden="true"><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="3"/></svg>; }
