import Link from 'next/link';
import { ArrowUpRight, Leaf, CalendarDays, Scissors, MapPin, Code2, ShieldCheck, Sparkles } from 'lucide-react';
import BotanicalScene from '../../components/botanical-scene';

export const metadata = { title: 'Our story' };
export default function AboutPage() {
  return <>
    <section className="about-hero"><div><p className="eyebrow">THE IDEA BEHIND EDEN</p><h1>A familiar place.<br /><em>A fresh perspective.</em></h1><p>A neighbourhood salon, imagined through a more thoughtful digital experience.</p></div><BotanicalScene compact /></section>
    <section className="section story-section" data-reveal><div className="story-photo"><img src="https://images.unsplash.com/photo-1633681926022-84c23e8cb2e9?auto=format&fit=crop&w=1100&q=85" alt="Carefully styled hair in a bright salon setting" loading="lazy" /><span className="photo-credit">ILLUSTRATIVE PHOTOGRAPHY · UNSPLASH</span></div><div><p className="eyebrow">ROOTED IN A LOCAL IDEA</p><h2>Less waiting.<br />More <em>feeling good.</em></h2><p>Great salon experiences start before you sit in the chair. They start when you discover a service, find a convenient time, and know exactly what to expect.</p><p>This project explores how an independent salon website could make those little moments feel simpler—with live availability, a clear booking journey, private appointment management, and an organised salon calendar.</p><Link href="/book" className="text-link">Try the booking experience<ArrowUpRight size={18} /></Link></div></section>
    <section className="section values-section" data-reveal><p className="eyebrow">SMALL DETAILS, THOUGHTFULLY DONE</p><h2>Care goes beyond <em>the chair.</em></h2><div className="values-grid"><div><CalendarDays size={25} strokeWidth={1.2} /><h3>Time that works for you</h3><p>See available slots, choose a sample stylist, and book a visit around your day.</p></div><div><ShieldCheck size={25} strokeWidth={1.2} /><h3>A little peace of mind</h3><p>Private booking access, clear confirmation, and straightforward cancellation.</p></div><div><Leaf size={25} strokeWidth={1.2} /><h3>A considered experience</h3><p>A calm interface, accessible interactions, and motion that respects your preferences.</p></div></div></section>
    <section className="concept-section" id="concept"><div><p className="eyebrow">A NOTE ABOUT THIS PROJECT</p><h2>An independent<br /><em>portfolio concept.</em></h2><p>Built by Pritam Badagi as a full stack project, inspired by the publicly listed Eden Salon in Margao. This site is not affiliated with, endorsed by, or operated by that business.</p><p>The service menu, pricing, staff profiles, and appointments are fictional demo data. Images are illustrative stock photography. Submitting a booking here does not contact the salon or reserve a real appointment.</p><div className="concept-tech"><span><Code2 size={15} />Next.js + NestJS</span><span><ShieldCheck size={15} />Firebase Firestore</span><span><Sparkles size={15} />Interactive 3D motion</span></div></div><aside className="location-card"><span className="eyebrow">PUBLIC RESEARCH REFERENCE</span><MapPin size={30} strokeWidth={1.1} /><h3>Margao, Goa</h3><p>Matruchaya Building,<br />Opp. New Era High School,<br />Malbhat, Margao,<br />Goa 403601</p><a href="https://salonist.io/cs/s/EDENSALONHOMESTAYPVTLTD" target="_blank" rel="noopener noreferrer" className="text-link">View the public Salonist listing<ArrowUpRight size={16} /></a><small>Location reference only. Please use the business's own channels for actual appointments.</small></aside></section>
  </>;
}
